# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/wifi/ftm:
  enable:
    - if: IDF_TARGET in ["esp32c3", "esp32s2", "esp32s3"]
      temporary: true
      reason: the other targets are not tested yet

examples/wifi/getting_started:
  disable_test:
    - if: IDF_TARGET != "esp32"
      temporary: true
      reason: lack of runners

examples/wifi/iperf:
  disable_test:
    - if: IDF_TARGET != "esp32"
      temporary: true
      reason: lack of runners
