# Location of top-level MicroPython directory
MPY_DIR = $(HOME)/micropython

# Name of module
MOD = multiplication

# Source files (.c or .py
SRC = multiplication.c

# Architecture to build for
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
