# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/security/flash_encryption:
  disable_test:
    - if: IDF_TARGET in ["esp32s2", "esp32s3", "esp32c2"]
      temporary: true
      reason: lack of runners
