# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/cxx/exceptions:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      temporary: true
      reason: lack of runners

examples/cxx/pthread:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      temporary: true
      reason: lack of runners
examples/cxx/rtti:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3"]
      temporary: true
      reason: lack of runners
