// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: TRGB_ESP32S3

#include "../ui.h"

void ui_Loading_Screen_screen_init(void)
{
ui_Loading_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Loading_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Loading_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Loading_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_Loading_Screen,1000,90);
lv_obj_set_width( ui_Spinner1, lv_pct(20));
lv_obj_set_height( ui_Spinner1, lv_pct(20));
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xB6B6CF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x416DB4), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner1, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Spinner1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Loading_Screen);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 0 );
lv_obj_set_y( ui_Label7, 87 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Saving Configuration");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Spinner1, ui_event_Spinner1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Loading_Screen, ui_event_Loading_Screen, LV_EVENT_ALL, NULL);

}
