// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: TRGB_ESP32S3

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
ui_SettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_SettingScreen);
lv_obj_set_width( ui_Panel1, 346);
lv_obj_set_height( ui_Panel1, 5);
lv_obj_set_x( ui_Panel1, 1 );
lv_obj_set_y( ui_Panel1, -98 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x426CB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_Label1, lv_pct(68));
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -144 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Please configure the initial settings before the user uses this device.");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensitivityValue = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_SensitivityValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensitivityValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SensitivityValue, 200 );
lv_obj_set_y( ui_SensitivityValue, -20 );
lv_obj_set_align( ui_SensitivityValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensitivityValue,"0");
lv_obj_set_style_text_color(ui_SensitivityValue, lv_color_hex(0x426CB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SensitivityValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SensitivityValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SensitivityValue, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensitivitySlider = lv_slider_create(ui_SettingScreen);
lv_slider_set_mode(ui_SensitivitySlider, LV_SLIDER_MODE_SYMMETRICAL);
lv_obj_set_width( ui_SensitivitySlider, 150);
lv_obj_set_height( ui_SensitivitySlider, 22);
lv_obj_set_x( ui_SensitivitySlider, 83 );
lv_obj_set_y( ui_SensitivitySlider, -20 );
lv_obj_set_align( ui_SensitivitySlider, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_SensitivitySlider, lv_color_hex(0x416DB4), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensitivitySlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SensitivityTxt = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_SensitivityTxt, lv_pct(35));
lv_obj_set_height( ui_SensitivityTxt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SensitivityTxt, -107 );
lv_obj_set_y( ui_SensitivityTxt, -20 );
lv_obj_set_align( ui_SensitivityTxt, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensitivityTxt,"Sensitivity Level");
lv_obj_set_style_text_color(ui_SensitivityTxt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SensitivityTxt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SensitivityTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SensitivityTxt, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MicrophoneSettings = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_MicrophoneSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MicrophoneSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MicrophoneSettings, -4 );
lv_obj_set_y( ui_MicrophoneSettings, -68 );
lv_obj_set_align( ui_MicrophoneSettings, LV_ALIGN_CENTER );
lv_label_set_text(ui_MicrophoneSettings,"Microphone Settings");
lv_obj_set_style_text_color(ui_MicrophoneSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MicrophoneSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MicrophoneSettings, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GainTxt = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_GainTxt, lv_pct(35));
lv_obj_set_height( ui_GainTxt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GainTxt, -107 );
lv_obj_set_y( ui_GainTxt, 20 );
lv_obj_set_align( ui_GainTxt, LV_ALIGN_CENTER );
lv_label_set_text(ui_GainTxt,"Gain Level");
lv_obj_set_style_text_color(ui_GainTxt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GainTxt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_GainTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GainTxt, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GainSlider = lv_slider_create(ui_SettingScreen);
lv_slider_set_mode(ui_GainSlider, LV_SLIDER_MODE_SYMMETRICAL);
lv_obj_set_width( ui_GainSlider, 150);
lv_obj_set_height( ui_GainSlider, 22);
lv_obj_set_x( ui_GainSlider, 83 );
lv_obj_set_y( ui_GainSlider, 20 );
lv_obj_set_align( ui_GainSlider, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_GainSlider, lv_color_hex(0x416DB4), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GainSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GainValue = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_GainValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GainValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GainValue, 200 );
lv_obj_set_y( ui_GainValue, 20 );
lv_obj_set_align( ui_GainValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_GainValue,"0");
lv_obj_set_style_text_color(ui_GainValue, lv_color_hex(0x426CB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GainValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_GainValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GainValue, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NoiseCancelling = lv_label_create(ui_SettingScreen);
lv_obj_set_width( ui_NoiseCancelling, lv_pct(35));
lv_obj_set_height( ui_NoiseCancelling, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NoiseCancelling, -107 );
lv_obj_set_y( ui_NoiseCancelling, 73 );
lv_obj_set_align( ui_NoiseCancelling, LV_ALIGN_CENTER );
lv_label_set_text(ui_NoiseCancelling,"Noise Cancelling");
lv_obj_set_style_text_color(ui_NoiseCancelling, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NoiseCancelling, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NoiseCancelling, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NoiseCancelling, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NextBT1 = lv_btn_create(ui_SettingScreen);
lv_obj_set_width( ui_NextBT1, 143);
lv_obj_set_height( ui_NextBT1, 55);
lv_obj_set_x( ui_NextBT1, 0 );
lv_obj_set_y( ui_NextBT1, 156 );
lv_obj_set_align( ui_NextBT1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_NextBT1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_NextBT1, lv_color_hex(0x426CB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextBT1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_NextBT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NextBT1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NextBT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_NextBT1);
lv_obj_set_width( ui_Label2, lv_pct(100));
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Confirm");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SwitchNoise = lv_switch_create(ui_SettingScreen);
lv_obj_set_width( ui_SwitchNoise, lv_pct(15));
lv_obj_set_height( ui_SwitchNoise, lv_pct(8));
lv_obj_set_x( ui_SwitchNoise, 30 );
lv_obj_set_y( ui_SwitchNoise, 71 );
lv_obj_set_align( ui_SwitchNoise, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SwitchNoise, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SwitchNoise, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SwitchNoise, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SwitchNoise, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SensitivitySlider, ui_event_SensitivitySlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GainSlider, ui_event_GainSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_NextBT1, ui_event_NextBT1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SwitchNoise, ui_event_SwitchNoise, LV_EVENT_ALL, NULL);

}
