// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: TRGB_ESP32S3

#include "../ui.h"

void ui_Welcome_Screen_screen_init(void)
{
ui_Welcome_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Welcome_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Welcome_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Welcome_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Welcome_Screen);
lv_img_set_src(ui_Image2, &ui_img_logo_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, 2 );
lv_obj_set_y( ui_Image2, -99 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,100);

ui_NextBT = lv_btn_create(ui_Welcome_Screen);
lv_obj_set_width( ui_NextBT, 143);
lv_obj_set_height( ui_NextBT, 55);
lv_obj_set_x( ui_NextBT, -1 );
lv_obj_set_y( ui_NextBT, 110 );
lv_obj_set_align( ui_NextBT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_NextBT, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_NextBT, lv_color_hex(0x426CB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextBT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_NextBT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NextBT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NextBT, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_NextBT);
lv_obj_set_width( ui_Label4, lv_pct(100));
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Next");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Description = lv_label_create(ui_Welcome_Screen);
lv_obj_set_width( ui_Description, lv_pct(80));
lv_obj_set_height( ui_Description, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Description, 6 );
lv_obj_set_y( ui_Description, 20 );
lv_obj_set_align( ui_Description, LV_ALIGN_CENTER );
lv_label_set_text(ui_Description,"Prototype of a wearable device for navigation disabled people.");
lv_obj_set_style_text_color(ui_Description, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Description, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Description, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Description, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_NextBT, ui_event_NextBT, LV_EVENT_ALL, NULL);

}
