// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: TRGB_ESP32S3

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void microphoneSetting_func(lv_event_t * e);
void noiseCancelling_func(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
